### ISSUE TITLE
Takes a LONG time

### ISSUE THREAD

**Issue by grangej** [146BC/RomeBuild#2]
Hi, just trying to figure out if I am doing something wrong.

I tested this using a repo that has a single carthage requirement, that is VERY small. It took 5 mins to build and upload.

Then running romebuild --build took long enough that I just gave up. Any ideas?

Server is on a dedicated mac mini.

**Comment by BernardGatt** [comment]
This really depends on the framework you're building, if the framework supports multiple platforms and has dependencies of it's own it will take more time, one of the best use-cases for this tool is to integrate it in CI so that every commit that gets merged into develop a fresh copy is stored on the rome server.

**Comment by grangej** [comment]
I resolved the issue, it was network timeout problem between me and the remote system.

**Comment by grangej** [comment]
closing this issue and opening a new one re: CI
